[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mycalculator = "EHP372SnNkpQpkNhcqPKqPZcjhqoYtYxZg2B2KrBiewi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
rpc = "https://api.devnet.solana.com/"
timeout=30000


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
